name: Publish container to GHCR

"on":
  release:
    types: [published]
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  publish-ghcr:
    name: Build and publish image
    runs-on: ubuntu-24.04
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/nuxnet-training
    steps:
      - name: Check out source-code repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate image tags
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,event=branch
            type=raw,value=main,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
